<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="5" time="0.258" timestamp="2025-04-28T11:08:45.048136+05:30" hostname="CHN-LAP-SSUBHAS"><testcase classname="test_multiplication" name="test_multiplication_11[1-11]" time="0.002" /><testcase classname="test_multiplication" name="test_multiplication_11[2-22]" time="0.002" /><testcase classname="test_multiplication" name="test_multiplication_11[3-33]" time="0.001" /><testcase classname="test_multiplication" name="test_multiplication_11[4-44]" time="0.001" /><testcase classname="test_multiplication" name="test_multiplication_11[5-5]" time="0.002"><failure message="assert (11 * 5) == 5">num = 5, output = 5

    @pytest.mark.parametrize("num, output", [(1, 11), (2, 22),(3, 33), (4, 44), (5,5)])
    def test_multiplication_11(num, output):
&gt;       assert 11*num == output
E       assert (11 * 5) == 5

test_multiplication.py:5: AssertionError</failure></testcase></testsuite></testsuites>